server:
  port: 8080

spring:
  application:
    name: inventory-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: ideas2it
    password: 
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-for-production
  expiration: 86400000 # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    com.ideas2it.inventory_service: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 